name: Run Pytest

on:
  pull_reuqest:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repositroy
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: Install dependencies
        run: pip install -r reuqirements.txt
      
      - name: Run pytest
        run: pyteest